# Theme default configuration
# Sites can override these values in their own _config.yml

# Minima date format
minima:
  date_format: "%b %-d, %Y"
  skin: dark

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pdf-embed
  - jekyll-paginate-v2

# Pagination configuration
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  trail:
    before: 2
    after: 2
  sort_field: 'date'
  sort_reverse: true

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# Permalink style
permalink: pretty

# Future posts
future: true
